FROM debian:bookworm

ARG INSTALL_ARGS=""
ENV INSTALL_ARGS=${INSTALL_ARGS}

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sudo openssh-server ca-certificates

COPY ./dotfiles /dotfiles
COPY ./install.sh /install.sh
RUN chmod +x ./install.sh

CMD ["bash", "-c", "./install.sh ${INSTALL_ARGS}"]
