FROM debian:bookworm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    openssh-server \
    ca-certificates \
    sudo \
    curl \
    git \
    wget \
    zsh

# Simulate run script via pipeline (curl)
CMD ["bash", "-c", "cat $DOTFILES_VOLUME_DIR/install.sh | bash -s -- $INSTALL_SCRIPT_PARAMS"]
