FROM debian:bookworm

# To expand optional arguments for install.sh in CMD.
ARG INSTALL_ARGS=""
ENV INSTALL_ARGS=${INSTALL_ARGS}

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    openssh-server \
    ca-certificates \
    sudo \
    curl \
    # bat \
    # exa \
    # fd-find \
    # fzf \
    # git \
    # htop \
    # httpie \
    # jq \
    # neovim \
    # peco \
    # ripgrep \
    # tree \
    # wget \
    zsh

COPY . /var/tmp/.dotfiles

# Simulate run via curl
CMD ["bash", "-c", "cat /var/tmp/.dotfiles/install.sh | bash -s -- $INSTALL_ARGS"]
